### PR TITLE
Disable test file that hogs up all memory

### PR DESCRIPTION
**Pull request by usev6**

### CODE REVIEW

**Comment by dwarring** [comment]
I getting this with Rakudo HEAD:
```
david@pc:~/git/roast$ raku -v
Welcome to Rakudo™ v2024.09-97-gb56ba4c58.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.09-5-g174aa1ba9.
david@pc:~/git/roast$ time raku integration/advent2012-day21.t 
1..9
ok 1 - main usage
Killed

real	0m11.446s
user	0m7.057s
sys	0m3.548s
```
Seems to eat up memory very quickly (32Gb)

Compared to 2024.09:
```
david@pc:~/git/roast$ raku -v
Welcome to Rakudo™ v2024.09.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.09.
david@pc:~/git/roast$ time raku integration/advent2012-day21.t 
1..9
ok 1 - main usage
ok 2 - sequence
ok 3 - recursive-ternary-hand-cached
ok 4 - sequence-ternary
ok 5 - loop
ok 6 - recursive-ternary
ok 7 - hand-memoization
ok 8 - gerdr
ok 9 - kaz
# recursive-ternary: 0.239854419 seconds
# loop: 0.240001791 seconds
# gerdr: 0.242101961 seconds
# kaz: 0.242638278 seconds
# hand-memoization: 0.249875383 seconds
# sequence-ternary: 0.305388659 seconds
# recursive-ternary-hand-cached: 0.339483588 seconds
# sequence: 0.423099127 seconds

real	0m3.012s
user	0m3.680s
sys	0m0.348s
```
Looks like a performance regression. Are others getting similar results?

**Comment by usev6** [comment]
Oh, that's interesting. I know that the tests were fine for me in the past (like until a year ago), but I wasn't aware that it even worked with 2024.09.

So hopefully the problem can be identified and fixed (instead of disabling the test file permanently). Do you think it makes more sense to create an issue?

**Comment by lizmat** [comment]
yes, please

**Comment by usev6** [comment]
Ok, I've created an issue for Rakudo: https://github.com/rakudo/rakudo/issues/5665

I'd still like to see the test file temporarily disabled. It's not so nice to cause critical memory shortages for people who run the tests.

**Comment by usev6** [comment]
Thanks. Hopefully we can bring the tests back soon.

**Comment by usev6** [comment]
Just for the record: The test file is enabled again (9bf4b1ea07)

**Pull request merged**
