### PR TITLE
Fixes integration test

### LINKED ISSUE #640: Roast depends on Rakudo when it shouldn't
Checking out roast and running `perl fudgeandrun $(sed 's/#.*//' spectest.data | grep '\.t')` using the system wide installed rakudo master yields the following test failures:
```
[ 1809s] Test Summary Report
[ 1809s] -------------------
[ 1809s] S03-metaops/misc.t                                       (Wstat: 256 Tests: 0 Failed: 0)
[ 1809s]   Non-zero exit status: 1
[ 1809s]   Parse errors: No plan found in TAP output
[ 1809s] S26-documentation/block-leading-user-format.t            (Wstat: 256 Tests: 0 Failed: 0)
[ 1809s]   Non-zero exit status: 1
[ 1809s]   Parse errors: No plan found in TAP output
[ 1809s] integration/advent2010-day03.t                           (Wstat: 512 Tests: 2 Failed: 2)
[ 1809s]   Failed tests:  1-2
[ 1809s]   Non-zero exit status: 2
[ 1809s]   Parse errors: Bad plan.  You planned 12 tests but ran 2.
[ 1809s] Files=1361, Tests=188669, 1777 wallclock secs (24.89 usr  2.58 sys + 2077.74 cusr 109.43 csys = 2214.64 CPU)
[ 1809s] Result: FAIL
```

`S03-metaops/misc.t` and `S26-documentation/block-leading-user-format.t` fail because they try to load a module called `Test::Helpers` which seems to be part of rakudo's tests. `integration/advent2010-day03.t` fails because it expects the files `Makefile CREDITS LICENSE README.md` which are clearly part of rakudo and not roast.

This is blocking automated spectests for every rakudo commit on the Open Build Service.

### PR DESCRIPTION
**Pull request by JJ**
And this one really closes #640
It's simply a matter of changing the files and its contents to an equivalent in this directory.

### CODE REVIEW

**Comment by JJ** [comment]
@vrurg I see what you mean. It would probably be better to create an IO::Path for portability, right? Can do that if needed.

**Comment by vrurg** [comment]
Would be great if you can.

**Comment by JJ** [comment]
Done, can you check it now?

**Comment by vrurg** [comment]
Missed email notification on this. Looks good, I'm merging.

Thank you!

**Pull request merged**
