### PR TITLE
Test implementing non-multi method stubbed in role

### PR DESCRIPTION
**Pull request by usev6**
... as multi method in class. Compare
https://github.com/Raku/old-issue-tracker/issues/2901

### CODE REVIEW

**Comment by vrurg** [comment]
Considering that the error in issue is a compile-time one, wouldn't it be better to test using `eval-lives-ok`?

**Comment by usev6** [comment]
The main idea of using ```eval-lives-ok``` would be, that there would be exactly one failing test instead of the whole test file blowing up when this would regress or when the tests are run with an old version? Or is there another advantage?

But anyway, your suggestion makes sense to me. I'll open a new pull request. (Also, I've messed this one up, but committing to my master branch.)

**Comment by usev6** [comment]
New attempt at https://github.com/Raku/roast/pull/831

**Comment by vrurg** [comment]
> The main idea of using `eval-lives-ok` would be, that there would be exactly one failing test instead of the whole test file blowing up when this would regress or when the tests are run with an old version? Or is there another advantage?

No, that's the only one.

**Pull request closed without merging**
