### PR TITLE
Add test for R-metaop as value in colon pair

### PR DESCRIPTION
**Pull request by atroxaper**
In support for [#4204](https://github.com/rakudo/rakudo/pull/4204)

### CODE REVIEW

**Comment by MasterDuke17** [comment]
I'd prefer tests that didn't depend on the string representation of something (especially the `.gist`, which is only meant as a human-readable representation). Maybe check that the value of `foo` is `1` instead?

**Comment by atroxaper** [comment]
@MasterDuke17 I agree. I’m going to create a Capture and check equality.

**Comment by vrurg** [comment]
@atroxaper Why not just use a named? `sub foo(:$foo) { note $foo }; foo(:foo(3 R- 2))` currently fails, so the test could be done as (note: quick and dirty example):

```
my $got;
sub foo(:$foo) { $got = $foo };
lives-ok { foo(:foo(3 R- 2)) }, "call doesn't throw";
is $got, -1, "named is good";
```

**Comment by atroxaper** [comment]
@vrurg Did so. Thank you.

**Pull request merged**
