### PR TITLE
Add tests for new methods on class DateTime with PR #4288

### PR DESCRIPTION
**Pull request by tbrowder**
This PR adds a new test file for Rakudo PR #4288.

### CODE REVIEW

**Comment by vrurg** [comment]
This is a new file, must also be mentioned in spectest.data.

**Comment by tbrowder** [comment]
On Fri, Apr 2, 2021 at 09:21 Vadim Belman ***@***.***> wrote:

> This is a new file, must also be mentioned in spectest.data.
>
Yes, I plan to do that after the Rakudo PR is merged.

**Comment by tbrowder** [comment]
I put this on hold because the PR may change again. @lizmat and @ugexe are discussing adding more methods of the same type.

**Comment by tbrowder** [comment]
I an waiting for a merge, but don't plan to change the current Rakudo PR. Any more changes should be done separately.

**Pull request merged**
