### PR TITLE
Add tests for new routine 'frac'

### PR DESCRIPTION
**Pull request by tbrowder**
This PR adds a new test file to accompany the Rakudo PR 4244 which adds new routine **frac**.

### CODE REVIEW

**Review by vrurg — APPROVED** [review]
Just two aesthetic notes.

Aren't you lazy? ;) I would put all data in a table like:

```raku
my @tests = 
    0 => (0, -100),
    0.5 => (3/2, 1.5e0),
    ... # etc.
    ;
```

And then I would just iterate over it.

**Comment by tbrowder** [comment]
On Thu, Mar 11, 2021 at 21:58 Vadim Belman ***@***.***> wrote:

> Aren't you lazy? ;) I would put all data in a table like:
>
Yes, I am! I normally would eventually do that, but...

**Review by vrurg — APPROVED** [review]

**Comment by vrurg** [comment]
@tbrowder thanks! I didn't mean you had to change it, but it's anyway better now. :) All we need is for rakudo/rakudo#4244 to be merged.

**Comment by tbrowder** [comment]
I have requested the accompanying PR be reverted due to need for more discussion given new information and dissenting members.

**Comment by tbrowder** [comment]
Overcome by events.

**Pull request closed without merging**
