### PR TITLE
Add more tests for gather/take

### PR DESCRIPTION
**Pull request by usev6**
All of these tests are dying with an UnwindException on the
JVM backend currently, but they are passing on MoarVM.

### CODE REVIEW

**Comment by vrurg** [comment]
I would say that since they are known to fail it makes sense to fudge them.

**Comment by usev6** [comment]
Yes, I could do that. (Just in case you missed it: I took the easy route and specified in spectest.data to only run the test file on Moar.)

**Comment by vrurg** [comment]
I did miss it. But it looks somewhat weird because they're not moar specific in neither way. My approach would be to fudge them with `skip` for jvm. And add a canary test using `is_run` which would be fudged with `todo`. In this case if the bug is fixed we'll get a notification.

**Comment by vrurg** [comment]
Thanks @usev6! I'm awaiting for my jvm backend to compile in order to test this PR. Will merge later if it passes.

**Comment by usev6** [comment]
@vrurg Thanks! (I didn't want to generate that much extra work for you. My main reason for creating a PR was to get a second pair of eyes for the sanity of the tests.)

**Comment by vrurg** [comment]
The "much work" as you name it is only about running a compiler and then a single test. :)

Ok, done. Once again - thanks!

**Pull request merged**
