### PR TITLE
Add Gregorian test data including negative dates

### PR DESCRIPTION
**Pull request by tbrowder**
Extends tests of class DateTime to negative Gregorian dates

### CODE REVIEW

**Review by JJ — COMMENTED** [review]
Looks fine to me.

**Comment by tbrowder** [comment]
On Thu, Apr 29, 2021 at 11:24 Juan Julián Merelo Guervós <
***@***.***> wrote:

> *@JJ* commented on this pull request.
>
> Looks fine to me.
>
Thanks, JJ.

>
>

**Review by vrurg — APPROVED** [review]

**Comment by vrurg** [comment]
Do we have corresponding fixes in rakudo already?

**Comment by tbrowder** [comment]
On Thu, Apr 29, 2021 at 17:06 Vadim Belman ***@***.***> wrote:

> Do we have corresponding fixes in rakudo already?
>
Yes, these extend tests for additional coverage.

**Comment by vrurg** [comment]
Ok, I'd let this PR to hang around for one day before merging to give a chance for more people to review.

**Comment by tbrowder** [comment]
On Thu, Apr 29, 2021 at 17:48 Vadim Belman ***@***.***> wrote:

> Ok, I'd let this PR to hang around for one day before merging to give a
> chance for more people to review.
>
FYI, I plan to add more tests over a wider range of negative Gregorian and
Julian dates.

>

**Pull request merged**
