### PR TITLE
Add tests for auto-generated private accessors.

### PR DESCRIPTION
**Pull request by autark**

### CODE REVIEW

**Comment by AlexDaniel** [comment]
I am half way through reviewing this PR. However, I don't understand why the test for ``RT #125227`` is removed. Could you shine a light on that?

That being said, this removed test seems to be wrong. ``$o ~~ /':2'/`` will probably match ``World.nqp:2498`` just as well.

**Comment by autark** [comment]
These tests are written in support of PR rakudo/rakudo#674. That PR adds support for auto-generating private accessors, it also attaches defined semantics to 'is rw'/'is readonly' for private attributes. In that regard the test was removed as it specifically tests that 'is rw' will generate a warning -- something it should no longer do.

**Comment by JJ** [comment]
This issue mentions an issue that has been closed as Rejected, and also has a good amount of conflicts. Closing it.

**Comment by AlexDaniel** [comment]
What? This is a PR for https://github.com/rakudo/rakudo/pull/674 which is open. So this should be open as well.

**Comment by vrurg** [comment]
Worth a problem-solving issue, I'd say.

**Comment by JJ** [comment]
Since https://github.com/rakudo/rakudo/pull/674 is closed, closing this one too. It's also conflicting, so it does not help anyone keeping it open.

**Pull request closed without merging**
